<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class TravelSeed extends AbstractSeed
{
    public function run(): void
    {
        $travels = [
            [
                "name" => "Bahamas",
                "continent" => "North America",
                "slug" => "bahamas",
                "description" => "Bahamas is a great place to visit.",
                "price" => 25000,
                "image_path" => "teste",
                "startDate" => "2024-06-26",
                "returnDate" => "2024-06-29",
                "hotel" => "0",
                "population" => 385340,
                "extension" => 13939,
                "weather" => "Tropical",
                "nativeLanguage" => "English"
            ],
            [
                "name" => "Rio de Janeiro",
                "continent" => "South America",
                "country" => "Brazil",
                "slug" => "rio-de-janeiro",
                "description" => "Rio de Janeiro is a beautiful place in Brazil.",
                "price" => 10000,
                "image_path" => "teste",
                "startDate" => "2024-08-25",
                "returnDate" => "2024-08-29",
                "hotel" => "1",
                "population" => 6748000,
                "extension" => 1182.3,
                "weather" => "Tropical",
                "nativeLanguage" => "Portuguese"
            ],
            [
                "name" => "New York",
                "continent" => "North America",
                "country" => "United States",
                "slug" => "new-york",
                "description" => "New York is one of the most famous places in the United States.",
                "price" => 15000,
                "image_path" => "teste",
                "startDate" => "2024-07-02",
                "returnDate" => "2024-07-29",
                "hotel" => "1",
                "population" => 8400000,
                "extension" => 302.6,
                "weather" => "Humid Subtropical",
                "nativeLanguage" => "English"
            ],
            [
                "name" => "Madrid",
                "continent" => "Europe",
                "country" => "Spain",
                "slug" => "madrid",
                "description" => "Madrid is located in Spain and is one of the most incredible places in the world.",
                "price" => 20000,
                "image_path" => "teste",
                "startDate" => "2024-06-30",
                "returnDate" => "2024-07-29",
                "hotel" => "1",
                "population" => 3223000,
                "extension" => 604.3,
                "weather" => "Mediterranean",
                "nativeLanguage" => "Spanish"
            ],
            [
                "name" => "Tokyo",
                "continent" => "Asia",
                "country" => "Japan",
                "slug" => "tokyo",
                "description" => "Tokyo is a vibrant city known for its modern architecture and rich culture.",
                "price" => 18000,
                "image_path" => "tokyo.jpg",
                "startDate" => "2024-09-01",
                "returnDate" => "2024-09-15",
                "hotel" => "1",
                "population" => 13929286,
                "extension" => 2194,
                "weather" => "Humid Subtropical",
                "nativeLanguage" => "Japanese"
            ],
            [
                "name" => "Paris",
                "continent" => "Europe",
                "country" => "France",
                "slug" => "paris",
                "description" => "Paris, the capital of France, is famous for its art, fashion, and landmarks.",
                "price" => 22000,
                "image_path" => "paris.jpg",
                "startDate" => "2024-10-05",
                "returnDate" => "2024-10-20",
                "hotel" => "1",
                "population" => 2148000,
                "extension" => 105.4,
                "weather" => "Oceanic",
                "nativeLanguage" => "French"
            ],
            [
                "name" => "Sydney",
                "continent" => "Oceania",
                "country" => "Australia",
                "slug" => "sydney",
                "description" => "Sydney is known for its Sydney Opera House and beautiful harbor.",
                "price" => 23000,
                "image_path" => "sydney.jpg",
                "startDate" => "2024-11-10",
                "returnDate" => "2024-11-25",
                "hotel" => "1",
                "population" => 5312163,
                "extension" => 12368,
                "weather" => "Subtropical",
                "nativeLanguage" => "English"
            ],
            [
                "name" => "Cape Town",
                "continent" => "Africa",
                "country" => "South Africa",
                "slug" => "cape-town",
                "description" => "Cape Town is a stunning coastal city in South Africa.",
                "price" => 19000,
                "image_path" => "cape-town.jpg",
                "startDate" => "2024-12-01",
                "returnDate" => "2024-12-15",
                "hotel" => "1",
                "population" => 433688,
                "extension" => 400.3,
                "weather" => "Mediterranean",
                "nativeLanguage" => "Afrikaans, English, Xhosa"
            ],
            [
                "name" => "Dubai",
                "continent" => "Asia",
                "country" => "United Arab Emirates",
                "slug" => "dubai",
                "description" => "Dubai is known for its modern architecture and luxury shopping.",
                "price" => 24000,
                "image_path" => "dubai.jpg",
                "startDate" => "2024-12-20",
                "returnDate" => "2025-01-05",
                "hotel" => "1",
                "population" => 3331400,
                "extension" => 4114,
                "weather" => "Desert",
                "nativeLanguage" => "Arabic"
            ],
            [
                "name" => "London",
                "continent" => "Europe",
                "country" => "United Kingdom",
                "slug" => "london",
                "description" => "London is a historic city with iconic landmarks and a rich culture.",
                "price" => 21000,
                "image_path" => "london.jpg",
                "startDate" => "2025-01-10",
                "returnDate" => "2025-01-25",
                "hotel" => "1",
                "population" => 8982000,
                "extension" => 1572,
                "weather" => "Temperate Oceanic",
                "nativeLanguage" => "English"
            ],
            [
                "name" => "Bangkok",
                "continent" => "Asia",
                "country" => "Thailand",
                "slug" => "bangkok",
                "description" => "Bangkok is known for its vibrant street life and cultural landmarks.",
                "price" => 16000,
                "image_path" => "bangkok.jpg",
                "startDate" => "2025-02-05",
                "returnDate" => "2025-02-20",
                "hotel" => "0",
                "population" => 10539000,
                "extension" => 1568.7,
                "weather" => "Tropical",
                "nativeLanguage" => "Thai"
            ],
            [
                "name" => "Rome",
                "continent" => "Europe",
                "country" => "Italy",
                "slug" => "rome",
                "description" => "Rome is known for its nearly 3,000 years of globally influential art and culture.",
                "price" => 20000,
                "image_path" => "rome.jpg",
                "startDate" => "2025-03-10",
                "returnDate" => "2025-03-25",
                "hotel" => "1",
                "population" => 2873000,
                "extension" => 1285,
                "weather" => "Mediterranean",
                "nativeLanguage" => "Italian"
            ],
            [
                "name" => "Cancun",
                "continent" => "North America",
                "country" => "Mexico",
                "slug" => "cancun",
                "description" => "Cancun is known for its beautiful beaches and vibrant nightlife.",
                "price" => 14000,
                "image_path" => "cancun.jpg",
                "startDate" => "2025-04-01",
                "returnDate" => "2025-04-15",
                "hotel" => "0",
                "population" => 888797,
                "extension" => 1967,
                "weather" => "Tropical",
                "nativeLanguage" => "Spanish"
            ],
            [
                "name" => "Toronto",
                "continent" => "North America",
                "country" => "Canada",
                "slug" => "toronto",
                "description" => "Toronto is a major Canadian city with a dynamic mix of tourist attractions.",
                "price" => 17000,
                "image_path" => "toronto.jpg",
                "startDate" => "2025-05-10",
                "returnDate" => "2025-05-25",
                "hotel" => "1",
                "population" => 2930000,
                "extension" => 630.2,
                "weather" => "Humid Continental",
                "nativeLanguage" => "English, French"
            ],
            [
                "name" => "Berlin",
                "continent" => "Europe",
                "country" => "Germany",
                "slug" => "berlin",
                "description" => "Berlin is the capital of Germany, known for its art scene and modern landmarks.",
                "price" => 19000,
                "image_path" => "berlin.jpg",
                "startDate" => "2025-06-01",
                "returnDate" => "2025-06-15",
                "hotel" => "1",
                "population" => 3645000,
                "extension" => 891.7,
                "weather" => "Oceanic",
                "nativeLanguage" => "German"
            ],
        ];

        $table = $this->table("travels");
        $table->insert($travels)->saveData();
    }
}
