<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class TravelSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
        $travels = [
            [
                "name" => "Bahamas",
                "continent" => "North America",
                "slug" => "bahamas",
                "description" => "Bahamas is a great place for visit.",
                "price" => 25.000,
                "image_path" => "teste",
                "startDate" => "2024-06-26",
                "returnDate" => "2024-06-29",
                "hotel" => "0",
            ],
            [
                "name" => "Rio de Janeiro",
                "continent" => "South America",
                "country" => "Brazil",
                "slug" => "rio-de-janeiro",
                "description" => "Rio de Janeiro is a beutiful place in Brazil.",
                "price" => 10.000,
                "image_path" => "teste",
                "startDate" => "2024-08-25",
                "returnDate" => "2024-08-29",
                "hotel" => "1",
            ],
            [
                "name" => "New York",
                "continent" => "North America",
                "country" => "United States",
                "slug" => "new-york",
                "description" => "New York is a of places most famous in United States.",
                "price" => 15.000,
                "image_path" => "teste",
                "startDate" => "2024-07-02",
                "returnDate" => "2024-07-29",
                "hotel" => "1",
            ],
            [
                "name" => "Madrid",
                "continent" => "Europe",
                "country" => "Spain",
                "slug" => "madrid",
                "description" => "Madrid is located in Spain and a places more incridible in the World.",
                "price" => 20.000,
                "image_path" => "teste",
                "startDate" => "2024-06-30",
                "returnDate" => "2024-07-29",
                "hotel" => "1",
            ],
            [
                "name" => "Tokyo",
                "continent" => "Asia",
                "country" => "Japan",
                "slug" => "tokyo",
                "description" => "Tokyo is a vibrant city known for its modern architecture and rich culture.",
                "price" => 18.000,
                "image_path" => "tokyo.jpg",
                "startDate" => "2024-09-01",
                "returnDate" => "2024-09-15",
                "hotel" => "1",
            ],
            [
                "name" => "Paris",
                "continent" => "Europe",
                "country" => "France",
                "slug" => "paris",
                "description" => "Paris, the capital of France, is famous for its art, fashion, and landmarks.",
                "price" => 22.000,
                "image_path" => "paris.jpg",
                "startDate" => "2024-10-05",
                "returnDate" => "2024-10-20",
                "hotel" => "1",
            ],
            [
                "name" => "Sydney",
                "continent" => "Oceania",
                "country" => "Australia",
                "slug" => "sydney",
                "description" => "Sydney is known for its Sydney Opera House and beautiful harbor.",
                "price" => 23.000,
                "image_path" => "sydney.jpg",
                "startDate" => "2024-11-10",
                "returnDate" => "2024-11-25",
                "hotel" => "1",
            ],
            [
                "name" => "Cape Town",
                "continent" => "Africa",
                "country" => "South Africa",
                "slug" => "cape-town",
                "description" => "Cape Town is a stunning coastal city in South Africa.",
                "price" => 19.000,
                "image_path" => "cape-town.jpg",
                "startDate" => "2024-12-01",
                "returnDate" => "2024-12-15",
                "hotel" => "1",
            ],
            [
                "name" => "Dubai",
                "continent" => "Asia",
                "country" => "United Arab Emirates",
                "slug" => "dubai",
                "description" => "Dubai is known for its modern architecture and luxury shopping.",
                "price" => 24.000,
                "image_path" => "dubai.jpg",
                "startDate" => "2024-12-20",
                "returnDate" => "2025-01-05",
                "hotel" => "1",
            ],
            [
                "name" => "London",
                "continent" => "Europe",
                "country" => "United Kingdom",
                "slug" => "london",
                "description" => "London is a historic city with iconic landmarks and a rich culture.",
                "price" => 21.000,
                "image_path" => "london.jpg",
                "startDate" => "2025-01-10",
                "returnDate" => "2025-01-25",
                "hotel" => "1",
            ],
            [
                "name" => "Bangkok",
                "continent" => "Asia",
                "country" => "Thailand",
                "slug" => "bangkok",
                "description" => "Bangkok is known for its vibrant street life and cultural landmarks.",
                "price" => 16.000,
                "image_path" => "bangkok.jpg",
                "startDate" => "2025-02-05",
                "returnDate" => "2025-02-20",
                "hotel" => "0",
            ],
            [
                "name" => "Rome",
                "continent" => "Europe",
                "country" => "Italy",
                "slug" => "rome",
                "description" => "Rome is known for its nearly 3,000 years of globally influential art and culture.",
                "price" => 20.000,
                "image_path" => "rome.jpg",
                "startDate" => "2025-03-10",
                "returnDate" => "2025-03-25",
                "hotel" => "1",
            ],
            [
                "name" => "Cancun",
                "continent" => "North America",
                "country" => "Mexico",
                "slug" => "cancun",
                "description" => "Cancun is known for its beautiful beaches and vibrant nightlife.",
                "price" => 14.000,
                "image_path" => "cancun.jpg",
                "startDate" => "2025-04-01",
                "returnDate" => "2025-04-15",
                "hotel" => "0",
            ],
            [
                "name" => "Toronto",
                "continent" => "North America",
                "country" => "Canada",
                "slug" => "toronto",
                "description" => "Toronto is a major Canadian city with a dynamic mix of tourist attractions.",
                "price" => 17.000,
                "image_path" => "toronto.jpg",
                "startDate" => "2025-05-10",
                "returnDate" => "2025-05-25",
                "hotel" => "1",
            ],
            [
                "name" => "Berlin",
                "continent" => "Europe",
                "country" => "Germany",
                "slug" => "berlin",
                "description" => "Berlin is the capital of Germany, known for its art scene and modern landmarks.",
                "price" => 19.000,
                "image_path" => "berlin.jpg",
                "startDate" => "2025-06-01",
                "returnDate" => "2025-06-15",
                "hotel" => "1",
            ],
            [
                "name" => "Buenos Aires",
                "continent" => "South America",
                "country" => "Argentina",
                "slug" => "buenos-aires",
                "description" => "Buenos Aires is known for its European-style architecture and vibrant culture.",
                "price" => 13.000,
                "image_path" => "buenos-aires.jpg",
                "startDate" => "2025-07-01",
                "returnDate" => "2025-07-15",
                "hotel" => "0",
            ],
            [
                "name" => "Lisbon",
                "continent" => "Europe",
                "country" => "Portugal",
                "slug" => "lisbon",
                "description" => "Lisbon is the capital of Portugal, known for its hilly, coastal landscape.",
                "price" => 18.000,
                "image_path" => "lisbon.jpg",
                "startDate" => "2025-08-01",
                "returnDate" => "2025-08-15",
                "hotel" => "1",
            ],
            [
                "name" => "Istanbul",
                "continent" => "Europe",
                "country" => "Turkey",
                "slug" => "istanbul",
                "description" => "Istanbul is a major city in Turkey that straddles Europe and Asia.",
                "price" => 20.000,
                "image_path" => "istanbul.jpg",
                "startDate" => "2025-09-01",
                "returnDate" => "2025-09-15",
                "hotel" => "1",
            ],
            [
                "name" => "San Francisco",
                "continent" => "North America",
                "country" => "United States",
                "slug" => "san-francisco",
                "description" => "San Francisco is known for its Golden Gate Bridge and vibrant culture.",
                "price" => 22.000,
                "image_path" => "san-francisco.jpg",
                "startDate" => "2025-10-01",
                "returnDate" => "2025-10-15",
                "hotel" => "1",
            ],
            [
                "name" => "Seoul",
                "continent" => "Asia",
                "country" => "South Korea",
                "slug" => "seoul",
                "description" => "Seoul is a bustling metropolis known for its modern skyscrapers and pop culture.",
                "price" => 18.000,
                "image_path" => "seoul.jpg",
                "startDate" => "2025-11-01",
                "returnDate" => "2025-11-15",
                "hotel" => "0",
            ],
        ];

        $table = $this->table("travels");
        $table->insert($travels)->saveData();
    }
}
